[package]
name = "chiprust-emu-cli"
version = "0.1.0"
authors = ["Maxim Kuznetsov <maximxlssoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chiprust-emu = {version = "*", path = "../chiprust-emu"}
rodio = "0.13.1"
crossterm = "0.19.0"
clap = "2.33.3"
ctrlc = { version = "3.1.9", features = ["termination"] }
